services:
  - type: web
    name: sigma-live-server
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MEMORY_LIMIT
        value: "3000"
      - key: SIGMA_COLOR_24H_ENABLED
        value: "true"
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
